added resource deletion commands
redhat-sap/sap-edge pull request #24
Opened 2024-08-28 09:55 UTC by RishabhKodes

* Added the commands for the deletion of:
    1. Resource Group
    2. ARO Cluster

* Moved the README.md from `/` to the `/edge-integration-cell` directory

2024-08-28 11:02 UTC, kksat requested changes

2024-08-28 11:02 UTC, kksat commented on edge-integration-cell/README.md
looks like you accidentally copied readme file from project root, please remove

2024-08-28 11:02 UTC, kksat commented on bicep.makefile
with these two targets added, i believe target 'aro-remove' can be removed

2024-08-28 11:10 UTC, RishabhKodes commented on edge-integration-cell/README.md
@kksat This was intentional because this README only contains information about the code present in the `/edge-integration-cell`. This has no reference/relation to the code outside that directory.

Yes, I should've also updated the root directory README with the updated content, but that is a point of discussion what needs to go in that README.

2024-08-28 13:28 UTC, RishabhKodes commented on edge-integration-cell/README.md
Ack

2024-08-29 11:01 UTC, kksat approved these changes

2024-08-29 11:01 UTC, merged